### PR TITLE
Logout screen, cleanup session and error message on invalid login url

### PR DESCRIPTION
**Pull request by babelouest**
- Handle error in login url
- Forbid to continue if the connected user has no required scope
- Clear visible state upon logging out.
- Implement minimal logout screen - poke @yrammos on this one ;)

### CODE REVIEW

**Comment by yrammos** [comment]
@babelouest thank you for this ambitious PR. 

A number of things seem broken on my end. Am attaching screenshots for some of those things.

1. We seem to have lost the "continue" screen with the user's photo. In its place, I see the log-in form with the username field disabled and the password field still available. A bug, I suppose, since the user is already logged in.

Screen Shot 2020-06-19 at 10 29 56 AM

2. The user selection drop-down is (half-)visible even when no user is logged in at all. This is a regression to an issue that was fixed in #136; none of the available dropdown options ("Manage users" and "Add users") is meaningful when no users are in the session. I really liked the flow before this PR, it was wonderfully speedy, intuitive, and reassuring… Hoping there are no plans to change it! What is the intention behind the change, if I may ask?

Screen Shot 2020-06-19 at 10 30 30 AM

3. I cannot arrive at the log out screen at all. Is it still wired to the "killall" button?

4. I am locked out of the admin app in the latest commit. My admin account is indeed authorized, but I am not presented with a green Continue button (screenshot below).  I am asked to "register a scheme in my profile" but this should not be necessary because my admin scope does not use n-factor authentication.

Screen Shot 2020-06-19 at 10 32 40 AM

**Comment by yrammos** [comment]
@babelouest I like the idea of showing logged in but non-authorized users as "disabled"! It would be a kind of luxury I haven't seen in any other multi-session environments.

**Comment by yrammos** [comment]
@babelouest Thank you also for merging-in #144. Would appreciate hearing your thoughts about the underlying concern, whenever time allows.

**Comment by babelouest** [comment]
Hello @yrammos ,

I've pushed some changes in the branch

> We seem to have lost the "continue" screen with the user's photo.

Fixed, it was a forgotten flag.

> The user selection drop-down is (half-)visible even when no user is logged in at all

Fixed

I've also disabled non-authorized users in the dropdown lists in the admin and profile page. Now when a user doesn't have the required scope, it can't be selected in the dropdown list, see screenshot
Capture d’écran du 2020-06-20 09-14-03

> I cannot arrive at the log out screen at all. Is it still wired to the "killall" button?

Yes, you have the "killall" button when you're at the manage connected user page, a red "logout all users" in the bottom-right

> I am locked out of the admin app in the latest commit. My admin account is indeed authorized, but I am not presented with a green Continue button (screenshot below). I am asked to "register a scheme in my profile" but this should not be necessary because my admin scope does not use n-factor authentication.

It seems that you have added a scheme for the `g_admin` scope and the user `admin` doesn't have the scheme registered. You can reset your `g_admin` scope as explained in the documentation: https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md#impossible-to-log-in-as-administrator---n-factor-issue

**Comment by babelouest** [comment]
@yrammos , I haven't seen other bugs in this branch, I'm merging it into master then

**Pull request merged**
