### PR TITLE
Clear admin logged out

### PR DESCRIPTION
**Pull request by yrammos**
This PR is analogous to #121 (addressed by @babelouest in 919ab43). Its purpose is to clear the admin page navbar and main view if no admin user is logged in.

### CODE REVIEW

**Comment by babelouest** [comment]
Although I agree #121 was a good idea, I'm not sure having a blank page on the admin app when the user isn't logged in is a good idea, of target have at least some text, an image or a logo or something to appease the eye of the user rather than a cryptic page content. Do you have an idea on how to fill the void? On second thought, I'd also like something similar in the empty profile page too...

**Comment by yrammos** [comment]
@babelouest I agree that a blank card view underneath a navbar makes for a cryptic logout experience. I've been meaning to suggest a prominent login button. The button on the far-right corner of the navbar is elegant but way too inconspicuous, especially for the non-admin user. How does this sound to you?

Meanwhile, I'll soon post a PR that improves the recent solution to #121 (profile page). Logging out currently empties only the "Personal data" pane but not the "Schemes" panes, potentially leaving sensitive TOTP tokens and other sensitive data exposed.

**Comment by babelouest** [comment]
That's my problem here, my skills in we design are very low, so all I have is the idea to add *something nice* in the admin and profile page when logged out, not what, and even less how to do it. That's why I'm asking for help, if you have design skills :)

I've fixed the schemes data leak on logout in this commit: https://github.com/babelouest/glewlwyd/commit/b46a9e25d2dfacbe2c3769fae913575f2f8913c9 , thanks for pointing out

**Comment by yrammos** [comment]
@babelouest I'm not a designer by any stretch of the imagination but I'll try to put something together in the coming days. 

I haven't checked  b46a9e2 out yet but come think, it *might* expose the sessions list, if the accordion is left open. I've submitted PR that addresses the problem at the root, in case you may find it useful.

**Comment by yrammos** [comment]
Closing this for now, thank you. Will return with a proper log out view in due course.

**Comment by babelouest** [comment]
If we can't make something shiny, maybe we can come with something original like a fortune message or riddles...

**Pull request closed without merging**
