### PR TITLE
Do not display "toast" notifications unless the user is logged into the web app.

### PR DESCRIPTION
**Pull request by yrammos**
Unless the user is logged in, pop-up ("toast") notifications only duplicate warnings and errors already displayed in the main components of the web page. This PR suppresses notifications for users who have not logged into the web app.

### CODE REVIEW

**Comment by babelouest** [comment]
@yrammos , thanks, I've made some minor changes in the PR:
- always show the notifications in the Login page
- use the state instead of the props in the `Notification.render()` to be consistent with the rest of the code

**Comment by babelouest** [comment]
@yrammos , for some reason, your pull request duplicated all the commits in the master branch, I need to revert to the original state, we'll start over your pull requests after that...

**Comment by yrammos** [comment]
@babelouest this is because, under the mistaken assumption that `/docs/glewlwyd.conf` is git-ignored,  I accidentally committed my MySQL password into the master branch. So I had to remove that file from the entire master branch using `git filter-branch`. 

Might it be simpler if you just copy-pasted the files into your master branch directly? I could try to email you diff patches too, if that is more convenient. Apologies for the inconvenience.

**Comment by babelouest** [comment]
That's ok, I'll cherry pick the commits in your branches instead of merging the pr

**Comment by yrammos** [comment]
Thanks. Meanwhile to spare you this trouble in future PR's I'll do some git surgery and start afresh with your own master branch.

**Pull request merged**
